import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/share';
import { FormsModule } from '@angular/forms';

import { AppComponent } from './app.component';
import {
  TooltipDirective,
  NotificationDirective,
  ModalHostDirective,
  StopPropagationDirective
} from '../../directives';
import { MessageService, ModalService, TooltipService } from '../../services';
import {
  IconComponent,
  ButtonComponent,
  AntStarComponent,
  AntRateComponent,
  AntSwitchComponent,
  AntStepComponent,
  AntStepsComponent,
  BaseCheckboxComponent,
  AntRadioComponent,
  AntCheckboxComponent,
  AntAvatarComponent,
  AntAlertComponent,
  BaseLineProgressComponent,
  BaseCircleProgressComponent,
  AntProgressComponent,
  AntBreadcrumbItemComponent,
  AntBreadcrumbComponent,
  AntAffixComponent,
  BaseMenuItemComponent,
  BaseAlignComponent,
  BasePopupComponent,
  BaseTriggerComponent,
  AntTooltipComponent,
  AntTooltipWrapComponent,
  BaseNoticeComponent,
  MessageWrapComponent,
  AntModalWrapComponent,
  AntConfirmWrapComponent,
  AntSpinComponent,
  AntBackTopComponent,
  AntNotificationComponent,
  AntInputComponent,
  AntTextareaComponent,
  AntInputGroupComponent,
  AntInputNumberComponent,
  AntCardComponent,
  AntTimeLineComponent,
  AntTimeLineItemComponent,
  AntTagComponent,
  BaseTabsNavComponent,
  AntTabsComponent,
  BaseTabsContentComponent,
  AntCollapseComponent,
  AntCollapsePanelComponent,
  AntBadgeComponent,
  AntRowComponent,
  AntColComponent
} from '../../components';

@NgModule({
  declarations: [
    AppComponent,
    IconComponent,
    ButtonComponent,
    AntStarComponent,
    AntRateComponent,
    AntSwitchComponent,
    AntStepComponent,
    AntStepsComponent,
    BaseCheckboxComponent,
    AntRadioComponent,
    AntCheckboxComponent,
    AntAvatarComponent,
    AntAlertComponent,
    BaseLineProgressComponent,
    BaseCircleProgressComponent,
    AntProgressComponent,
    AntBreadcrumbItemComponent,
    AntBreadcrumbComponent,
    AntAffixComponent,
    BaseMenuItemComponent,
    BaseAlignComponent,
    BasePopupComponent,
    BaseTriggerComponent,
    AntTooltipComponent,
    TooltipDirective,
    AntTooltipWrapComponent,
    BaseNoticeComponent,
    NotificationDirective,
    MessageWrapComponent,
    AntModalWrapComponent,
    ModalHostDirective,
    StopPropagationDirective,
    AntConfirmWrapComponent,
    AntSpinComponent,
    AntBackTopComponent,
    AntNotificationComponent,
    AntInputComponent,
    AntTextareaComponent,
    AntInputGroupComponent,
    AntInputNumberComponent,
    AntCardComponent,
    AntTimeLineComponent,
    AntTimeLineItemComponent,
    AntTagComponent,
    BaseTabsNavComponent,
    AntTabsComponent,
    BaseTabsContentComponent,
    AntCollapseComponent,
    AntCollapsePanelComponent,
    AntBadgeComponent,
    AntRowComponent,
    AntColComponent
  ],
  imports: [BrowserModule, FormsModule],
  providers: [MessageService, ModalService, TooltipService],
  bootstrap: [AppComponent],
  entryComponents: [BaseNoticeComponent, AntSwitchComponent]
})
export class AppModule {}
